# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

# Internationalization
spring.messages.basename=messages/messages

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h

# percentile ??? ?? histogram bucket ???
management.metrics.distribution.percentiles-histogram.http.server.requests=true


owm.api-key=${OWM_API_KEY:}

# CircuitBreaker
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowSize=20
resilience4j.circuitbreaker.instances.weatherApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.weatherApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.weatherApi.permittedNumberOfCallsInHalfOpenState=5

# TimeLimiter (timeout)
resilience4j.timelimiter.instances.weatherApi.timeoutDuration=1s

# JPA SQL ??
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Hibernate ??
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
